package com.mondorevive.TRESPOT.cauzione.storicoCauzione.operazione;

public enum TipoOperazione {
    NON_SPECIFICATA,CREAZIONE,AGGIORNAMENTO_MANUALE,CARICO_VARCO,SCARICO_VARCO,CARICO_MANUALE,SCARICO_MANUALE,
    ASSOCIA_BOBINE,MESSA_IN_MANUTENZIONE,REVISIONE,RIPARAZIONE
}
